<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN_Cutter" Id="{f1df099b-19f3-47d0-858e-fbde7c1af039}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Cutter
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_Cutter">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>